[package]
name = "spki"
version = "0.4.0" # Also update html_root_url in lib.rs when bumping this
description = """
X.509 Subject Public Key Info (RFC5280) describing public keys as well as their
associated AlgorithmIdentifiers (i.e. OIDs)
"""
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
edition = "2018"
repository = "https://github.com/RustCrypto/utils/tree/master/spki"
categories = ["cryptography", "data-structures", "encoding", "no-std"]
keywords = ["crypto", "x509"]
readme = "README.md"

[dependencies]
der = { version = "0.4", features = ["oid"], path = "../der" }

[features]
std = ["der/std"]
