name: base64ct

on:
  pull_request:
    paths:
      - "base64ct/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: base64ct

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.47.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo build --target ${{ matrix.target }} --release
      - run: cargo build --target ${{ matrix.target }} --release --features alloc

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.47.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test --release
      - run: cargo test --release --features alloc
      - run: cargo test --release --all-features
