name: block-buffer

on:
  pull_request:
      paths:
        - "block-buffer/**"
        - "Cargo.*"
  push:
    branches: master

permissions:
  contents: read

defaults:
  run:
    working-directory: block-buffer

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.65.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      - run: cargo build --target ${{ matrix.target }}

  # TODO(tarcieri): re-enable after next `crypto-common` release
  #minimal-versions:
  #  uses: RustCrypto/actions/.github/workflows/minimal-versions.yml@master
  #  with:
  #      working-directory: ${{ github.workflow }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.65.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test
      - run: cargo test --all-features
