name: dbl

on:
  pull_request:
      paths:
        - "dbl/**"
        - "Cargo.*"
  push:
    branches: master

permissions:
  contents: read

defaults:
  run:
    working-directory: dbl

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.41.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v3
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
          targets: ${{ matrix.target }}
      # Isolate this crate from workspace which is otherwise MSRV 1.56 due to 2021 edition crates
      - run: rm ../Cargo.toml
      - run: cargo build --target ${{ matrix.target }}

  minimal-versions:
    uses: RustCrypto/actions/.github/workflows/minimal-versions.yml@master
    with:
        working-directory: ${{ github.workflow }}

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.41.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v3
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      # Isolate this crate from workspace which is otherwise MSRV 1.56 due to 2021 edition crates
      - run: rm ../Cargo.toml
      - run: cargo test
