name: fiat-constify

on:
  pull_request:
    paths:
      - ".github/workflows/fiat-constify.yml"
      - "fiat-constify/**"
      - "Cargo.*"
  push:
    branches: master

permissions:
  contents: read

defaults:
  run:
    working-directory: fiat-constify

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

# Cancels CI jobs when new commits are pushed to a PR branch
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: RustCrypto/actions/cargo-cache@master
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo test
