name: pkcs5

on:
  pull_request:
    paths:
      - "const-oid/**"
      - "der/**"
      - "pkcs5/**"
      - "spki/**"
      - "Cargo.*"
  push:
    branches: master

defaults:
  run:
    working-directory: pkcs5

env:
  CARGO_INCREMENTAL: 0
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.51.0 # MSRV
          - stable
        target:
          - thumbv7em-none-eabi
          - wasm32-unknown-unknown
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          target: ${{ matrix.target }}
          override: true
      - run: cargo build --target ${{ matrix.target }} --release
      - run: cargo build --target ${{ matrix.target }} --release --features alloc
      - run: cargo build --target ${{ matrix.target }} --release --features pbes2
      - run: cargo build --target ${{ matrix.target }} --release --features scrypt
      - run: cargo build --target ${{ matrix.target }} --release --features alloc,pbes2
      - run: cargo build --target ${{ matrix.target }} --release --features sha1
      - run: cargo build --target ${{ matrix.target }} --release --features 3des
      - run: cargo build --target ${{ matrix.target }} --release --features des-insecure

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - 1.51.0 # MSRV
          - stable
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
      - run: cargo test --release
      - run: cargo test --release --features alloc
      - run: cargo test --release --features pbes2
      - run: cargo test --release --features scrypt
      - run: cargo test --release --features sha1
      - run: cargo test --release --features 3des
      - run: cargo test --release --features des-insecure
      - run: cargo test --release --all-features
